### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by noamtcohen** [common-tater/wkwebview-getusermedia-shim#1]
Hi,

Could you please point me to doc on how to use this?
Maybe an XCode project?

Thanks,
N

**Comment by jessetane** [comment]
In swift, it would go something like this (borrowed from [here](https://github.com/common-tater/wkwebview-webrtc-shim)):

``` swift
var configuration = WKWebViewConfiguration()
var controller = WKUserContentController()
configuration.userContentController = controller

var webView = WKWebView(frame: container.frame, configuration: configuration)
container.addSubview(webView)

// apply shim
WKWebViewGetUserMediaShim(webView: webView, contentController: controller)

var request = NSURLRequest(URL: NSURL(string:"http://my-site.com")!)
webView.loadRequest(request)
```

Be warned, this is not even close to a complete shim, it's audio only and the stream it returns can only be connected to a scriptProcessorNode.

**Comment by noamtcohen** [comment]
Thanks! this is exactly what I need for now.

**Comment by antoniohof** [comment]
Hi @jessetane , and could you help me with an objective-c example?
My code is already this:
```
WKWebViewConfiguration *configuration = [[WKWebViewConfiguration alloc] init];
WKUserContentController *controller = [[WKUserContentController alloc] init];
[controller addScriptMessageHandler:self name:@"unityControl"];
configuration.userContentController = controller;
webView = [[WKWebView alloc] initWithFrame:view.frame configuration:configuration];
```

**Comment by jessetane** [comment]
`[[WKWebViewGetUserMediaShim alloc] initWithWebView:webView contentController:controller];`

From the header file: https://github.com/common-tater/wkwebview-getusermedia-shim/blob/master/WKWebViewGetUserMediaShim/WKWebViewGetUserMediaShim.h#L33
