### ISSUE TITLE
Context not closing

### ISSUE THREAD

**Issue by noamtcohen** [common-tater/wkwebview-getusermedia-shim#2]
Hi,

It seems that the audio context is not reseting correctly when I call `stream.stop(); context.close();`.  Is this the correct way to close the audio stream?
When I reload the page every thing start to work ok again.

N

**Comment by jessetane** [comment]
I can't imagine `context.close` really having any effect here, but `stream.stop` is implemented and should work - have you tried using devtools to debug? This is probably the method in question:

https://github.com/common-tater/wkwebview-getusermedia-shim/blob/master/WKWebViewGetUserMediaShim/WKWebViewGetUserMediaShim.js#L122

**Comment by jessetane** [comment]
Also, you can define WKWEBVIEW_GET_USER_MEDIA_SHIM_DEBUG on the iOS side to get more debug output:

https://github.com/common-tater/wkwebview-getusermedia-shim/blob/master/WKWebViewGetUserMediaShim/WKWebViewGetUserMediaShim.m#L200

**Comment by noamtcohen** [comment]
Thanks, I'll run some tests and get back to you.

**Comment by noamtcohen** [comment]
I run some test and changed the javascript so that the steam is recycled and not re-created and that fixed the problem.

```
   var stream;
  function getUserMedia (constraints, successCallback, errorCallback) {
     postMessage('WKWebViewGetUserMediaShim_MediaStream_new', constraints, function (trackData) {
                if(stream){
                    successCallback(stream)
                    return;
                }
      stream = new MediaStream()
```
