### ISSUE TITLE
Works on Simulator but not on Device 

### ISSUE THREAD

**Issue by noamtcohen** [common-tater/wkwebview-getusermedia-shim#4]
I'm not sure why but when I run the application on the device ```startAudio``` succeeds with message ```did start capturing audio``` but audio data is never received and ```onaudio``` is never called.

**Comment by jessetane** [comment]
hm, maybe a microphone access permission issue?

**Comment by noamtcohen** [comment]
I'm allowing access when the phone asks me... Is there somewhere else I have to tell that I'm going to use the mic? (Settings->Privacy->Microphone is on)

**Comment by noamtcohen** [comment]
I found out that this problem occurs on the device (not simulator) when running together with this project: https://github.com/Bilibili/ijkplayer

**Comment by jessetane** [comment]
Unfortunately I don't have time to dig into this right now but if you find the issue let us know

**Comment by noamtcohen** [comment]
Thank you, I understand you don't have time. Just so you know I've opened an issue also with ijkplayer: https://github.com/Bilibili/ijkplayer/issues/2496
They suggest it has something todo with ```AVAudioSession```. I've been trying to figure this out for a few hours but didn't succeed yet. I'll let you know if I solve this. Thanks again.

**Comment by OEcity** [comment]
Any progress here? I'm stuck on the same problem. I'm using ijkplayer for RTSP stream from doorbell and liblinphone for calling. But with rtsp stream running, the microphone on mobile device doesn't work.

**Comment by noamtcohen** [comment]
@OEcity in IJKMediaPlayer/Classes/IJKMediaPlayer/IJKAudioKit.m make this change:
```objectivec
- (void)setupAudioSession
{
    if (!_audioSessionInitialized) {
        [[NSNotificationCenter defaultCenter] addObserver: self
                                                 selector: @selector(handleInterruption:)
                                                     name: AVAudioSessionInterruptionNotification
                                                   object: [AVAudioSession sharedInstance]];
        _audioSessionInitialized = YES;
    }

    /* Set audio session to mediaplayback */

    // Set audio session to play and record
    
    NSError *error = nil;
    if (NO == [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:&error]) {
        NSLog(@"IJKAudioKit: AVAudioSession.setCategory() failed: %@\n", error ? [error localizedDescription] : @"nil");
        return;
    }
    
    // Override the current inputs and outputs and route audio to the built-in speaker and microphone.
  
    [[AVAudioSession sharedInstance] overrideOutputAudioPort:AVAudioSessionPortOverrideSpeaker
                                         error:&error];
    
    error = nil;
    if (NO == [[AVAudioSession sharedInstance] setActive:YES error:&error]) {
        NSLog(@"IJKAudioKit: AVAudioSession.setActive(YES) failed: %@\n", error ? [error localizedDescription] : @"nil");
        return;
    }

    return ;
}
```
